// Fallback data so the frontend is fully developable before the Laravel
// API is wired up. Every value here reflects real information from the
// brief — no fabricated clients, metrics, or testimonials. Swap this out
// once GET /api/* is live; see lib/api.ts.

import type {
  Project,
  Service,
  SkillCategory,
  Experience,
  Education,
  SiteSettings,
  SocialLink,
  Testimonial,
} from "@/types";

const tech = (name: string, category = "Language") => ({
  id: Math.abs(hash(name)),
  name,
  slug: slugify(name),
  icon: null,
  category,
});

function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
function hash(s: string) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h << 5) - h + s.charCodeAt(i);
  return h;
}

export const siteSettings: SiteSettings = {
  name: "Kerod Ginbaru",
  professional_title: "Full-Stack & Mobile Developer",
  email: "kerodhope@gmail.com",
  phone: "0965201930",
  location: "Ethiopia",
  hero_heading: "I build software that solves real business problems.",
  hero_description:
    "Full-stack and mobile developer with a background in Information Technology and Management — I design systems that fit how a business actually runs, not just how the code compiles.",
  about_text:
    "My background spans both Information Technology and Management. That combination means I don't just implement features — I understand the business process behind the request, from requirements through to deployment.",
  contact_cta: "Have a project in mind? Let's talk about what you're building.",
  resume_url: null,
  profile_photo_url: null,
  admin_avatar_url: null,
};

export const socialLinks: SocialLink[] = [
  { id: 1, platform: "GitHub", url: "https://github.com/", icon: "github", sort_order: 1 },
  { id: 2, platform: "LinkedIn", url: "https://linkedin.com/", icon: "linkedin", sort_order: 2 },
  { id: 3, platform: "WhatsApp", url: "https://wa.me/251965201930", icon: "message-circle", sort_order: 3 },
  { id: 4, platform: "Email", url: "mailto:kerodhope@gmail.com", icon: "mail", sort_order: 4 },
];

export const services: Service[] = [
  { id: 1, title: "Web Application Development", slug: "web-application-development", description: "Custom web applications built on Laravel and Next.js, from internal tools to customer-facing platforms.", icon: "globe", featured: true },
  { id: 2, title: "Mobile Application Development", slug: "mobile-application-development", description: "Cross-platform mobile apps with Flutter, backed by REST APIs and offline-first data with Hive.", icon: "smartphone", featured: true },
  { id: 3, title: "Business Management Systems", slug: "business-management-systems", description: "Systems that model how your business actually operates — inventory, staff, records, workflows.", icon: "briefcase", featured: true },
  { id: 4, title: "REST API Development", slug: "rest-api-development", description: "Clean, documented, authenticated APIs designed to power web and mobile clients alike.", icon: "server", featured: false },
  { id: 5, title: "Database Development", slug: "database-development", description: "Relational schema design with proper normalization, indexing, and migration discipline.", icon: "database", featured: false },
  { id: 6, title: "System Analysis & Design", slug: "system-analysis-design", description: "Translating a business problem into requirements, architecture, and a build plan before writing code.", icon: "git-branch", featured: false },
  { id: 7, title: "Existing System Improvement", slug: "existing-system-improvement", description: "Auditing and improving systems already in production — performance, security, and maintainability.", icon: "wrench", featured: false },
];

export const skillCategories: SkillCategory[] = [
  { id: 1, name: "Programming Languages", skills: ["Dart", "PHP", "JavaScript", "TypeScript", "Python", "Java", "SQL"].map((n, i) => ({ id: i + 1, name: n, proficiency: null })) },
  { id: 2, name: "Frameworks", skills: ["Flutter", "Laravel", "Next.js", "Tailwind CSS", "Bootstrap", "Riverpod"].map((n, i) => ({ id: i + 10, name: n, proficiency: null })) },
  { id: 3, name: "Backend", skills: ["REST APIs", "JWT", "Authentication", "Authorization", "RBAC"].map((n, i) => ({ id: i + 20, name: n, proficiency: null })) },
  { id: 4, name: "Databases", skills: ["MySQL", "PostgreSQL", "Firebase", "Hive"].map((n, i) => ({ id: i + 30, name: n, proficiency: null })) },
  { id: 5, name: "Tools", skills: ["Git", "GitHub", "VS Code", "Postman", "Composer"].map((n, i) => ({ id: i + 40, name: n, proficiency: null })) },
];

export const experience: Experience[] = [];
export const education: Education[] = [];

// Testimonials intentionally empty — populate only from the admin panel
// once real testimonials exist. Never seed fake ones.
export const testimonials: Testimonial[] = [];

export const projects: Project[] = [
  {
    id: 1,
    title: "Yadot — ያዶት",
    slug: "yadot",
    short_description: "Business Management System",
    description:
      "A business management system built to digitize day-to-day operations — records, workflows, and reporting — for a real operating business.",
    problem: "Manual, paper-based processes made day-to-day operations slow and error-prone.",
    solution: "A Laravel-driven system that models the business's actual workflow, with role-based access and structured records.",
    category: { id: 1, name: "Business Systems", slug: "business-systems" },
    status: "completed",
    featured: true,
    year: 2024,
    github_url: null,
    live_url: null,
    architecture: "Laravel MVC backend with Blade/Bootstrap admin views and a MySQL relational schema.",
    challenges: "Modeling business rules accurately required close iteration with how the business actually operates day to day.",
    lessons_learned: "Requirements gathered directly from real workflows produce far more durable systems than assumptions.",
    technologies: [tech("Laravel", "Framework"), tech("PHP"), tech("MySQL", "Database"), tech("Bootstrap", "Framework"), tech("JavaScript")],
    images: [],
    cover_image: null,
  },
  {
    id: 2,
    title: "HOPE",
    slug: "hope",
    short_description: "AI Life Planner",
    description:
      "A mobile life-planning app that helps users structure goals and daily plans, built with an offline-first architecture.",
    problem: "Existing planning apps are either too rigid or require constant connectivity.",
    solution: "A Flutter app with Riverpod state management and Hive local storage, syncing to Firebase when online.",
    category: { id: 2, name: "Mobile", slug: "mobile" },
    status: "in_development",
    featured: true,
    year: 2025,
    github_url: null,
    live_url: null,
    architecture: "Flutter client, Riverpod for state, Hive for offline persistence, Firebase for sync and auth.",
    challenges: "Designing a clean offline-first sync strategy between Hive and Firebase.",
    lessons_learned: "In progress.",
    technologies: [tech("Flutter", "Framework"), tech("Dart"), tech("Firebase", "Database"), tech("Riverpod", "Framework"), tech("Hive", "Database")],
    images: [],
    cover_image: null,
  },
  {
    id: 3,
    title: "EthioShop",
    slug: "ethioshop",
    short_description: "Mobile E-Commerce",
    description: "A mobile e-commerce application for browsing and purchasing products, built with Flutter and Firebase.",
    problem: null,
    solution: null,
    category: { id: 2, name: "Mobile", slug: "mobile" },
    status: "in_development",
    featured: true,
    year: 2025,
    github_url: null,
    live_url: null,
    architecture: "Flutter client backed by Firebase for auth, data, and storage.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("Flutter", "Framework"), tech("Dart"), tech("Firebase", "Database")],
    images: [],
    cover_image: null,
  },
  {
    id: 4,
    title: "EOTC-RCAMS",
    slug: "eotc-rcams",
    short_description: "Church Administrative REST API",
    description: "A REST API powering administrative record-keeping for a church organization, with JWT-secured endpoints.",
    problem: null,
    solution: null,
    category: { id: 3, name: "API", slug: "api" },
    status: "completed",
    featured: true,
    year: 2024,
    github_url: null,
    live_url: null,
    architecture: "Laravel REST API with JWT authentication and a MySQL schema for administrative records.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("Laravel", "Framework"), tech("PHP"), tech("MySQL", "Database"), tech("JWT", "Backend")],
    images: [],
    cover_image: null,
  },
  {
    id: 5,
    title: "Document Management System",
    slug: "document-management-system",
    short_description: "Administrative System",
    description: "A system for organizing, storing, and retrieving administrative documents.",
    problem: null,
    solution: null,
    category: { id: 1, name: "Business Systems", slug: "business-systems" },
    status: "completed",
    featured: false,
    year: 2023,
    github_url: null,
    live_url: null,
    architecture: "PHP backend with a MySQL schema for document metadata and retrieval.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("PHP"), tech("MySQL", "Database")],
    images: [],
    cover_image: null,
  },
  {
    id: 6,
    title: "Digital Restaurant Menu — ያዲ ክትፎ",
    slug: "digital-restaurant-menu",
    short_description: "Digital menu system",
    description: "A digital menu system for a restaurant, replacing printed menus with a manageable digital equivalent.",
    problem: null,
    solution: null,
    category: { id: 1, name: "Business Systems", slug: "business-systems" },
    status: "completed",
    featured: false,
    year: 2023,
    github_url: null,
    live_url: null,
    architecture: "PHP with a MySQL-backed menu structure.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("PHP"), tech("MySQL", "Database")],
    images: [],
    cover_image: null,
  },
  {
    id: 7,
    title: "BiblioVerse",
    slug: "biblioverse",
    short_description: "Library management platform",
    description: "A Laravel-based platform for organizing and browsing a library's catalog.",
    problem: null,
    solution: null,
    category: { id: 1, name: "Business Systems", slug: "business-systems" },
    status: "completed",
    featured: false,
    year: 2024,
    github_url: null,
    live_url: null,
    architecture: "Laravel backend, Tailwind CSS front views, MySQL database.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("Laravel", "Framework"), tech("PHP"), tech("MySQL", "Database"), tech("Tailwind CSS", "Framework")],
    images: [],
    cover_image: null,
  },
  {
    id: 8,
    title: "HOPE System",
    slug: "hope-system",
    short_description: "Laravel-based management system",
    description: "A Laravel and MySQL management system, distinct from the HOPE mobile app.",
    problem: null,
    solution: null,
    category: { id: 1, name: "Business Systems", slug: "business-systems" },
    status: "completed",
    featured: false,
    year: 2024,
    github_url: null,
    live_url: null,
    architecture: "Laravel backend with a MySQL relational schema.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("Laravel", "Framework"), tech("MySQL", "Database")],
    images: [],
    cover_image: null,
  },
  {
    id: 9,
    title: "Employee Management & Attendance System",
    slug: "employee-management-attendance-system",
    short_description: "Planned: staff records and attendance tracking",
    description: "A planned system for managing employee records and tracking attendance, spanning a Flutter client and Laravel API.",
    problem: null,
    solution: null,
    category: { id: 1, name: "Business Systems", slug: "business-systems" },
    status: "planned",
    featured: false,
    year: null,
    github_url: null,
    live_url: null,
    architecture: "Planned: Flutter client, Laravel API, MySQL database.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("Flutter", "Framework"), tech("Laravel", "Framework"), tech("MySQL", "Database")],
    images: [],
    cover_image: null,
  },
  {
    id: 10,
    title: "Data Structures & Algorithms Visualizer",
    slug: "dsa-visualizer",
    short_description: "Planned: interactive DSA visualizer",
    description: "A planned interactive tool for visualizing data structures and algorithms in the browser.",
    problem: null,
    solution: null,
    category: { id: 4, name: "Tooling", slug: "tooling" },
    status: "planned",
    featured: false,
    year: null,
    github_url: null,
    live_url: null,
    architecture: "Planned: TypeScript/JavaScript, rendered in-browser.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("TypeScript"), tech("JavaScript")],
    images: [],
    cover_image: null,
  },
  {
    id: 11,
    title: "Network Monitoring System",
    slug: "network-monitoring-system",
    short_description: "Planned: network monitoring tool",
    description: "A planned tool for monitoring network status and activity, built in Python.",
    problem: null,
    solution: null,
    category: { id: 4, name: "Tooling", slug: "tooling" },
    status: "planned",
    featured: false,
    year: null,
    github_url: null,
    live_url: null,
    architecture: "Planned: Python.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("Python")],
    images: [],
    cover_image: null,
  },
  {
    id: 12,
    title: "Advanced Database Project",
    slug: "advanced-database-project",
    short_description: "Planned: advanced relational database project",
    description: "A planned advanced database project exploring MySQL and PostgreSQL design patterns.",
    problem: null,
    solution: null,
    category: { id: 4, name: "Tooling", slug: "tooling" },
    status: "planned",
    featured: false,
    year: null,
    github_url: null,
    live_url: null,
    architecture: "Planned: MySQL / PostgreSQL.",
    challenges: null,
    lessons_learned: null,
    technologies: [tech("MySQL", "Database"), tech("PostgreSQL", "Database")],
    images: [],
    cover_image: null,
  },
];

export const projectCategories = [
  { id: 1, name: "Business Systems", slug: "business-systems" },
  { id: 2, name: "Mobile", slug: "mobile" },
  { id: 3, name: "API", slug: "api" },
  { id: 4, name: "Tooling", slug: "tooling" },
];
